require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DemandsController do

  # This should return the minimal set of attributes required to create a valid
  # Demand. As you add validations to Demand, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "content" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DemandsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all demands as @demands" do
      demand = Demand.create! valid_attributes
      get :index, {}, valid_session
      assigns(:demands).should eq([demand])
    end
  end

  describe "GET show" do
    it "assigns the requested demand as @demand" do
      demand = Demand.create! valid_attributes
      get :show, {:id => demand.to_param}, valid_session
      assigns(:demand).should eq(demand)
    end
  end

  describe "GET new" do
    it "assigns a new demand as @demand" do
      get :new, {}, valid_session
      assigns(:demand).should be_a_new(Demand)
    end
  end

  describe "GET edit" do
    it "assigns the requested demand as @demand" do
      demand = Demand.create! valid_attributes
      get :edit, {:id => demand.to_param}, valid_session
      assigns(:demand).should eq(demand)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Demand" do
        expect {
          post :create, {:demand => valid_attributes}, valid_session
        }.to change(Demand, :count).by(1)
      end

      it "assigns a newly created demand as @demand" do
        post :create, {:demand => valid_attributes}, valid_session
        assigns(:demand).should be_a(Demand)
        assigns(:demand).should be_persisted
      end

      it "redirects to the created demand" do
        post :create, {:demand => valid_attributes}, valid_session
        response.should redirect_to(Demand.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved demand as @demand" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demand.any_instance.stub(:save).and_return(false)
        post :create, {:demand => { "content" => "invalid value" }}, valid_session
        assigns(:demand).should be_a_new(Demand)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demand.any_instance.stub(:save).and_return(false)
        post :create, {:demand => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested demand" do
        demand = Demand.create! valid_attributes
        # Assuming there are no other demands in the database, this
        # specifies that the Demand created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Demand.any_instance.should_receive(:update_attributes).with({ "content" => "MyString" })
        put :update, {:id => demand.to_param, :demand => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested demand as @demand" do
        demand = Demand.create! valid_attributes
        put :update, {:id => demand.to_param, :demand => valid_attributes}, valid_session
        assigns(:demand).should eq(demand)
      end

      it "redirects to the demand" do
        demand = Demand.create! valid_attributes
        put :update, {:id => demand.to_param, :demand => valid_attributes}, valid_session
        response.should redirect_to(demand)
      end
    end

    describe "with invalid params" do
      it "assigns the demand as @demand" do
        demand = Demand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demand.any_instance.stub(:save).and_return(false)
        put :update, {:id => demand.to_param, :demand => { "content" => "invalid value" }}, valid_session
        assigns(:demand).should eq(demand)
      end

      it "re-renders the 'edit' template" do
        demand = Demand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demand.any_instance.stub(:save).and_return(false)
        put :update, {:id => demand.to_param, :demand => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested demand" do
      demand = Demand.create! valid_attributes
      expect {
        delete :destroy, {:id => demand.to_param}, valid_session
      }.to change(Demand, :count).by(-1)
    end

    it "redirects to the demands list" do
      demand = Demand.create! valid_attributes
      delete :destroy, {:id => demand.to_param}, valid_session
      response.should redirect_to(demands_url)
    end
  end

end
